### ISSUE TITLE
PR preview Deployment

### ISSUE THREAD

**Issue by naveen521kk** [ManimCommunity/manim-website#2]
Currently there is no preview Deployment available for PR and this can be fixed by adding either vercel or Netlify which provides the support for it.

**Comment by leotrs** [comment]
Thanks for opening the issue :)

It does sound interesting - though I'm not sure if we plan on making tons of changes to the website that would require such a tool. Right now the website is pretty bare :joy:

**Comment by naveen521kk** [comment]
Seems useless now.
