### ISSUE TITLE
Blue Favicon in Safari

### ISSUE THREAD

**Issue by Kiran-Raj-Dev** [ManimCommunity/manim-website#25]
In safari the favicon appears to be blue coloured.
<img width="22" alt="Screenshot 2021-11-18 at 8 24 39 PM" src="https://user-images.githubusercontent.com/90276965/142439062-a5608207-f4e2-497b-8a47-2dec60c4c3f4.png">

This is a non issue on the documentation's website.
<img width="22" alt="Screenshot 2021-11-18 at 8 26 29 PM" src="https://user-images.githubusercontent.com/90276965/142439369-3267a43d-2fa2-4127-b52e-3218b4e3c849.png">

**Comment by naveen521kk** [comment]
Dunno why that happens, in firefox on windows it is like
![image](https://user-images.githubusercontent.com/49693820/142562004-8be84088-a2d1-42cf-b777-771fe63d29d0.png)
