### ISSUE TITLE
[Feature] Add some demos to the site?

### ISSUE THREAD

**Issue by Myzel394** [ManimCommunity/manim-website#6]
Currently the site honestly looks totally boring. If I told people about this amazing tool called Manim and they went to the "landing page" they were like: "uuhhh pretty static site - but can you show me what it can do?". And I agree! There should be videos, screenshots, code snippets, etc. to showcase what Manim is capable of and how easy it is use it!

.... yeah just my two cents.

**Comment by NikhilSharma03** [comment]
using information available in README.md will implement various sections such as documentation, usage, code snippets. Can you please link me videos related to manin that I can use ??
If there's more suggestion let me know and I will be pleased if you can assign this issue to me.

**Comment by naveen521kk** [comment]
It's done in the new version.
